apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: APPNAME-vs
  namespace: NAMESPACE
spec:
  hosts:
  - "service-a.pica.conso.com"
  gateways:
  - default-gateway
  http:
  - route:
    - destination:
        host: service-a-svc
        port:
          number: 80
        subset: version-v1
      weight: 100
